#   Karunatree
#   Copyright 2009-2010 Derek Lyons & Karunatree. All Rights Reserved.
#   
#   Author: Autogenerated

module UserHelper
  
  def previews
    users_seedlings = Array.new
    @user.seedlings.each do |seedling|
      users_seedlings = users_seedlings + @user.seedlings
    end
    users_seedlings.uniq!
    users_seedlings.delete(@seedling)
  
    link_string = ""
    for i in (1..[2, users_seedlings.count].max)
      r = rand(users_seedlings.count)
      seedling = users_seedlings[r]
      link_string << link_to(image_tag(seedling.project.url(:square), :width => "75px", :id => "morebyimg", :class => "more-link"), url_for(seedling))
      users_seedlings.delete(seedling)
    end
  
    return link_string
  end
  
end
